title: cmd 26277| null return
author: LLIK_LLA • X8|5
email: cwatson90@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You took my hand and we fell into it like a day dream or a fever

# social links
twitter_username: your-twitter-handle
github_username:  LLIK_LLA

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
